name: download-java
description: 'Download Temurin 19'
outputs:
  filepath:
    description: 'Path to JDK archive'
    value: ${{ env.FILE_PATH }}

runs:
  using: composite
  steps:
    - if: runner.os == 'Linux'
      name: 'Download Temurin for Linux'
      id: download-temurin-linux
      run: |
        FILE_PATH=$RUNNER_TEMP/temurin-19.tar.gz
        wget -O "$FILE_PATH" "https://github.com/adoptium/temurin19-binaries/releases/download/jdk-19.0.1%2B10/OpenJDK19U-jdk_x64_linux_hotspot_19.0.1_10.tar.gz"
        echo "FILE_PATH=$FILE_PATH" >> $GITHUB_ENV
      shell: bash

    - if: runner.os == 'Windows'
      name: 'Download Temurin for Windows'
      id: download-temurin-windows
      run: |
        $FILE_PATH="$env:RUNNER_TEMP/temurin-19.zip"
        (New-Object System.Net.WebClient).DownloadFile("https://github.com/adoptium/temurin19-binaries/releases/download/jdk-19.0.1%2B10/OpenJDK19U-jdk_x64_windows_hotspot_19.0.1_10.zip", "$FILE_PATH")
        echo "FILE_PATH=$FILE_PATH" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      shell: pwsh
