name: setup-temurin
description: Setup Temurin

inputs:
  jdk-ver:
    required: true

runs:
  using: composite
  steps:
    - name: Download Temurin
      run: |
        $os = "${{ runner.os }}".toLower()
        $json = $(Invoke-WebRequest "https://api.adoptium.net/v3/assets/latest/${{ inputs.jdk-ver }}/hotspot?architecture=x64&image_type=jdk&os=$os&vendor=eclipse").Content | ConvertFrom-Json
        $link = $json[0].binary.package.link
        $name = $json[0].binary.package.name
        $FILE_PATH = "$env:RUNNER_TEMP/$name"
        (New-Object System.Net.WebClient).DownloadFile("$link", "$FILE_PATH")
        "TARGET_OS=$os" >> $env:GITHUB_ENV
        "FILE_PATH=$FILE_PATH" >> $env:GITHUB_ENV
      shell: pwsh
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: jdkfile
        jdkFile: ${{ env.FILE_PATH }}
        java-version: ${{ inputs.jdk-ver }}
        architecture: x64
        cache: maven
