name: init-env
description: 'Initialize build environment'
outputs:
  java-home:
    description: JAVA_HOME
    value: /opt/jdk-19
  maven-home:
    description: MAVEN_HOME
    value: /opt/apache-maven-3.8.6

runs:
  using: composite
  steps:
    - name: 'Install OpenJDK'
      id: openjdk
      run: curl -sL https://download.java.net/java/GA/jdk19/877d6127e982470ba2a7faa31cc93d04/36/GPL/openjdk-19_linux-x64_bin.tar.gz | tar xz -C /opt/
      shell: bash

    - name: 'Install Maven'
      id: openjdk
      run: curl -sL https://dlcdn.apache.org/maven/maven-3/3.8.6/binaries/apache-maven-3.8.6-bin.tar.gz | tar xz -C /opt/
      shell: bash
