# Simple workflow for deploying static content to GitHub Pages
name: Deploy Javadoc to Pages

on:
  release:
    types: [created]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: 'Download Temurin 19'
        id: download-java
        uses: ./.github/actions/download-java
      - name: 'Setup Java'
        uses: actions/setup-java@v3
        with:
          distribution: 'jdkfile'
          jdkFile: ${{ env.FILE_PATH }}
          java-version: '19'
          architecture: 'x64'
          cache: 'maven'
      - name: Build javadoc
        run: mvn -B -Dmaven.test.skip=true package javadoc:javadoc
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: 'target/site/apidocs'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
