name: Publish package
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Setup Oracle OpenJDK 19
        uses: oracle-actions/setup-java@v1
        with:
          website: jdk.java.net
          release: 19
      - name: 'Run Maven'
        run: mvn -B -Dgroups="linux & amd64" package
      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy
        env:
          GITHUB_TOKEN: ${{ github.token }}
