name: Publish package
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: 'Download Temurin 19'
        id: download-java
        uses: ./.github/actions/download-java
      - name: 'Setup Java'
        uses: actions/setup-java@v3
        with:
          distribution: 'jdkfile'
          jdkFile: ${{ env.FILE_PATH }}
          java-version: '19'
          architecture: 'x64'
          cache: 'maven'
      - name: 'Run Maven'
        run: mvn -B -Dgroups="linux & amd64" package
      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy
        env:
          GITHUB_TOKEN: ${{ github.token }}
