name: Publish package
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Initialize
        id: init-env
        uses: ./.github/actions/init-env
      - name: Generate settings.xml
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          servers: '[{ "id": "github", "username": "${env.GITHUB_USER}", "password": "${env.GITHUB_TOKEN}" }]'
      - name: Publish package
        run: ${{ steps.init-env.outputs.maven-home }}/bin/mvn --batch-mode -Dgroups='linux & amd64' deploy
        env:
          JAVA_HOME: ${{ steps.init-env.outputs.java-home }}
          GITHUB_USER: ${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
